language: go
sudo: false

env:
  global:
    - GO111MODULE=on

before_script:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/lint/golint
  - make deps

after_success:
  - if [[ "$TRAVIS_GO_VERSION" == 1.10.* ]]; then $HOME/gopath/bin/goveralls -service=travis-ci; fi

go:
  - "1.9.x"
  - "1.10.x"
  - "1.11.x"
